version: 2
jobs:
  build:
    working_directory: ~/wsl-share/devel/film-ratin/cci
    docker:
      - image: circleci/clojure:lein-2.8.1
     environment:
       LEIN_ROOT: nbd
       JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_chashe:
          paths:
            - ~/.m2
          key: film-ratings-{{ checksum "project.clj" }}
      - run: lein do test, uberjar
